---
- name: "Get helm path"
  shell: |
    source {{ ansible_env.HOME }}/.asdf/asdf.sh
    asdf where helm
  args:
    executable: "{{ (ansible_system == 'Linux') | ternary('/usr/bin/bash', '/bin/bash') }}"
  register: helm_path

- name: "Get python path"
  shell: |
    source {{ ansible_env.HOME }}/.asdf/asdf.sh
    asdf where python
  args:
    executable: "{{ (ansible_system == 'Linux') | ternary('/usr/bin/bash', '/bin/bash') }}"
  register: python_path

- name: "Add helm repositories"
  kubernetes.core.helm_repository:
    binary_path: "{{ helm_path.stdout }}/bin/helm"
    name: "{{ item.name }}"
    repo_url: "{{ item.repo }}"
  with_items:
    "{{ helm_repositories }}"
  vars:
    ansible_python_interpreter: "{{ python_path.stdout }}/bin/python"
