---
- hosts: localhost
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - dot_files:
      - source: "authorized_keys"
        dest:   ".ssh/authorized_keys"
      - source: "aws"
        dest:   ".bin/aws"
        mode:   "0750"
      - source: "gitconfig"
      - source: "p10k.zsh"
      - source: "tmux.conf"
      - source: "vimrc"
      - source: "zpreztorc"
      - source: "zprofile"
      - source: "zshrc"
      - source: "zshrc.d/"
    - home_directories:
      - ".bin"
      - ".config"
      - ".fonts"
      - ".ssh"
      - ".vim"
      - ".vim/autoload"
    - asdf_plugins:
      - {"name": "helm",      "version": "latest"}
      - {"name": "kubectl",   "version": "latest"}
      - {"name": "python",    "version": "3.11.0"}
      - {"name": "terraform", "version": "1.3.4",
         "repo": "https://github.com/asdf-community/asdf-hashicorp.git"}

  tasks:
    - name: Create home directories
      file:
        name: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
      with_items:
        "{{ home_directories }}"

    - name: Add config files
      copy:
        src: "files/{{ item.source }}"
        dest: "{{ ansible_env.HOME }}/{{ item.dest | default('.' + item.source) }}"
        mode: "{{ item.mode | default('0660') }}"
      with_items: "{{ dot_files }}"

    - name: Install Prezto
      git:
        repo: https://github.com/sorin-ionescu/prezto.git
        dest: "{{ ansible_env.HOME }}/.zprezto"
        recursive: yes

    - name: "p10k: Download MesloLGS fonts"
      get_url:
        url: "https://github.com/romkatv/powerlevel10k-media/raw/master/{{ item|urlencode() }}.ttf"
        dest: "{{ ansible_env.HOME }}/.fonts/{{ item }}.ttf"
        mode: "0640"
      with_items:
        - "MesloLGS NF Regular"
        - "MesloLGS NF Bold"
        - "MesloLGS NF Italic"
        - "MesloLGS NF Bold Italic"

    - name: "vim: Install vim-plug"
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
        mode: 0644
        force: yes

    - name: "vim: Install Plugins"
      command: "vim +PlugUpdate +qall"

    - import_role:
        name: asdf
    - import_role:
        name: python
    - import_role:
        name: helm
    - import_role:
        name: scrypy

    - name: "Linux Setup"
      import_role:
        name: linux
      when: ansible_system == "Linux"

    - name: "MacOS Setup"
      import_role:
        name: macos
      when: ansible_system == "Darwin"
