---
- hosts: localhost
  vars:
    - required_roles:
      - dots
      - vim
  vars_files:
    - vars/defaults.yaml
  tasks:
    - name: Check for host variable file
      stat:
        path: "vars/{{ ansible_hostname | lower }}.yaml"
      register: host_var_file

    - name: Include host variable file
      include_vars:
        file: "vars/{{ ansible_hostname | lower }}.yaml"
      when: host_var_file.stat.exists

    - include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      with_items:
        - "{{ required_roles }}"
        - "{{ ['macos'] if ansible_system == 'Darwin' else ['linux'] }}"
        - "{{ optional_roles | default([]) }}"
