---
- name: "Linux: Install Packages"
  become: yes
  ansible.builtin.package:
    name: "{{ linux_packages_default + (linux_packages_extra | default([])) }}"
    state: present
  when: ansible_pkg_mgr != "pacman"

- name: "Arch: Install Packages"
  become: yes
  community.general.pacman:
    name: "{{ linux_packages_arch }}"
  when: ansible_pkg_mgr == "pacman"

# - name: "Linux: Setup Desktop"
#   import_role:
#     name: desktop
#   when: linux_desktop is defined and linux_desktop | bool
