---
- name: "Linux: Install Packages"
  become: yes
  apt:
    pkg: "{{ linux_packages }}"
    state: present
    update_cache: yes

- name: "Linux: Setup Desktop"
  import_role:
    name: desktop
  when: linux_destop is defined and linux_desktop | bool
