---
- name: "Linux: Install Packages"
  become: yes
  apt:
    pkg: "{{ linux_packages_default + (linux_packages_extra | default([])) }}"
    state: present
    update_cache: yes

- name: "Linux: Setup Desktop"
  import_role:
    name: desktop
  when: linux_desktop is defined and linux_desktop | bool
