---
- name: "Get python path"
  shell: |
    source {{ ansible_env.HOME }}/.asdf/asdf.sh
    asdf where python
  args:
    executable: "{{ (ansible_system == 'Linux') | ternary('/usr/bin/bash', '/bin/bash') }}"
  register: python_path

- name: "Install python packages"
  pip:
    name: "{{ python_packages }}"
    executable: "{{ python_path.stdout }}/bin/pip"
