---
github_releases:
- name: "derailed/k9s"
  version: "latest"
  asset: "k9s_Linux_x86_64.tar.gz"
  binaries:
    - k9s
- name: "ahmetb/kubectx"
  version: "v0.9.4"
  asset: "kubectx_v0.9.4_linux_x86_64.tar.gz"
  binaries:
    - kubectx
