---
desktop_files:
- source:    "kitty/kitty.conf"
  dest:      ".config/kitty/kitty.conf"
- source:    "kitty/dracula.conf"
  dest:      ".config/kitty/dracula.conf"
- source:    "kitty/diff.conf"
  dest:      ".config/kitty/diff.conf"

desktop_apt_keys:
- "https://packages.microsoft.com/keys/microsoft.asc"
- "https://downloads.1password.com/linux/keys/1password.asc"

desktop_apt_repos:
- "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
- "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/1password.asc] https://downloads.1password.com/linux/debian/amd64 stable main"

desktop_packages:
- 1password
- google-chrome-stable
- kitty
- microsoft-edge-stable
- slack-desktop
- telegram-desktop

dconf_settings:
# Set desktop background
- key: "/org/gnome/desktop/background/picture-options"
  value: "'zoom'"
- key: "/org/gnome/desktop/background/picture-uri-dark"
  value: "'file://{{ ansible_env.HOME }}/Dropbox/Pictures/wallpapers/ff7r_midgar.jpg'"
# Map Caps to ctrl"
- key: "/org/gnome/desktop/input-sources/xkb-options"
  value: "['ctrl:nocaps']"
# Enable touchpad natural scrolling"
- key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
  value: "true"
# Disable touchpad tap to click"
- key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
  value: "false"
# Enable touchpad two-finger scrolling"
- key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled"
  value: "true"

# Lock display orientation
- key: "/org/gnome/settings-daemon/peripherals/touchscreen/orientation-lock"
  value: "true"
# Disable <Super>t shortcut"
- key: "/org/gnome/settings-daemon/plugins/media-keys/terminal"
  value: "@as []"
# Create <Super>t shortcut for kitty"
- key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
  value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/PopLaunch1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
# Create <Super>t shortcut for kitty"
- key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
  value: "'kitty'"
# Create <Super>t shortcut for kitty"
- key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
  value: "'<Super>t'"
# Create <Super>t shortcut for kitty"
- key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
  value: "'/usr/bin/kitty'"
# Disable automatic screen brightness"
- key: "/org/gnome/settings-daemon/plugins/power/ambient-enabled"
  value: "false"

# Disable dynamic workspaces"
- key: "/org/gnome/mutter/dynamic-workspaces"
  value: "false"
# Workspaces only on primary display"
- key: "/org/gnome/mutter/workspaces-only-on-primary"
  value: "true"

# Show weekday in clock"
- key: "/org/gnome/desktop/interface/clock-show-weekday"
  value: "true"
# Dark Mode"
- key: "/org/gnome/desktop/interface/color-scheme"
  value: "'prefer-dark'"
# Show battery percentage
- key: "/org/gnome/desktop/interface/show-battery-percentage"
  value: "true"

# Center clock on toolbar"
- key: "/org/gnome/shell/extensions/pop-cosmic/clock-alignment"
  value: "'CENTER'"
# Hide application button"
- key: "/org/gnome/shell/extensions/pop-cosmic/show-applications-button"
  value: "false"
# Hide workspaces button"
- key: "/org/gnome/shell/extensions/pop-cosmic/show-workspaces-button"
  value: "false"

# Disable dock"
- key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
  value: "false"
# Disable dock"
- key: "/org/gnome/shell/extensions/dash-to-dock/intellihide"
  value: "false"
# Disable dock"
- key: "/org/gnome/shell/extensions/dash-to-dock/manualhide"
  value: "true"
