# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Activate asdf
. ${HOME}/.asdf/asdf.sh

# Activate virtualenvwrapper
source $(asdf where python)/bin/virtualenvwrapper.sh
export VIRTUALENVWRAPPER_VIRTUALENV=$(asdf where python)/bin/virtualenv

# Use gnome keyring ssh-agent
# export SSH_AGENT_LAUNGHER=gnome-keyring
# export SSH_AUTH_SOCK=/run/user/${UID}/keyring/ssh

# Pull in any config files in ~/.zshrc.d
[[ -d ~/.zshrc.d ]] && for file in ~/.zshrc.d/*;do source ${file};done

# Source machine specific configs
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# Load ls colors
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
