# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Activate asdf
. ${HOME}/.asdf/asdf.sh

# Activate virtualenvwrapper
source $(asdf where python)/bin/virtualenvwrapper.sh

# Use gnome keyring ssh-agent
export SSH_AGENT_LAUNGHER=gnome-keyring
export SSH_AUTH_SOCK=/run/user/${UID}/keyring/ssh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Source machine specific configs
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
