---
- name: "Create tmp directory"
  file:
    path: /tmp/ansible
    state: directory
    mode: '0700'

- name: "Download releases"
  get_url:
    url: "https://github.com/{{ item.name }}/releases/{{ 'latest/' if item.version == 'latest' }}download/{{ item.version + '/' if item.version != 'latest' }}{{ item.asset }}"
    dest: /tmp/ansible
    mode: "0750"
  when: not (item.asset.endswith(".tar.gz"))
  with_items:
    "{{ github_releases }}"

- name: "Download & extract releases"
  unarchive:
    src: "https://github.com/{{ item.name }}/releases/{{ 'latest/' if item.version == 'latest' }}download/{{ item.version + '/' if item.version != 'latest' }}{{ item.asset }}"
    dest: /tmp/ansible
    remote_src: yes
  when: item.asset.endswith(".tar.gz")
  with_items:
    "{{ github_releases }}"

- include_tasks: move.yaml
  vars:
    app: "{{ github_app }}"
  loop_control:
    loop_var: github_app
  with_items:
    "{{ github_releases }}"
