---
- name: "Move binaries to {{ ansible_env.HOME }}/.bin"
  copy:
    src: "/tmp/ansible/{{ binary.source | default(binary) }}"
    dest: "{{ ansible_env.HOME }}/.bin/{{ binary.dest | default(binary) }}"
    mode: "0750"
  loop_control:
    loop_var: binary
  when: app.binaries is defined
  with_items:
    "{{ app.binaries }}"
