---
- name: "Install dependencies"
  become: yes
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg-agent
    state: present

- name: "Add Docker GPG apt Key"
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker Repository"
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: "Install docker-ce"
  become: yes
  apt:
    pkg: docker-ce
    state: present
    update_cache: yes
