---
- name: "Install dependencies"
  become: yes
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg-agent
    state: present

- name: "Add Docker GPG apt Key"
  become: yes
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: "Add Docker Repository"
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: "Install docker-ce"
  become: yes
  apt:
    pkg:
      - docker-ce
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: "Add 'nathan' user to 'docker' group"
  become: yes
  user:
    name: nathan
    groups: docker
    append: yes
